### ISSUE TITLE
New features todo in v0.2.0

### ISSUE THREAD

**Issue by cupools** [cupools/emilia#3]
New features will come in `v0.2.0`
- [x] A common methods to transform stylesheet content directly, which will be able to supports `postcss` and gulp but lose supports for dealing with multiple stylesheets.
- [ ] Provide a hook to enable rewrite sprite stylesheet rule with `postcss`
- [x] Speed up compilation
